#!/usr/bin/env zsh

mydir=${(%):-%N}
mydir=`dirname $mydir`
dotfiles=`dirname $mydir`

echo
echo "=================================================="
echo "Tell iStat Menus to import config from:"
echo ${dotfiles}/istatmenus/settings.ismp
echo "=================================================="
